Fix elf not found problem
You need to use the `pwd` command instead of `.` for Verilator to find
the elf file. This fixes the following error:
```
ERROR: Unknown image type: '/sw/build/demo/hello_world/demo
```